name: 'Hello World'
description: 'Greet someone'
inputs:
  app:
    description: 'Application to deploy'
    required: true
  env:
    description: 'Environment (staging, production)'
    required: true
  cluster:
    description: 'K8s cluster to deploy to'
    required: true
  chart_path:
    description: 'Custom helm chart directory path'
    default: "helm-chart"
    required: false
  envs_with_values:
    description: 'Comma separated list of envs that have custom values.yaml files'
    required: false
  kubeconfig_pr:
    description: 'Kubeconfig for PR cluster'
    required: false
  kubeconfig_np:
    description: 'Kubeconfig for NP cluster'
    required: false
  # image_tag:
  #   description: 'Override image tag to deploy'
  #   required: false

runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
        echo "[DEBUG] app: ${{ inputs.app }}"
        echo "[DEBUG] env: ${{ inputs.env }}"
        echo "[DEBUG] cluster: ${{ inputs.cluster }}"
        echo "[DEBUG] chart_path: ${{ inputs.chart_path }}"
        echo "[DEBUG] envs_with_values: ${{ inputs.envs_with_values }}"

    - name: Set base helm parameters
      shell: bash
      run: |
        echo "[DEBUG]: Setting base helm parameters.."
        env="${{ inputs.env }}"
        app="${{ inputs.app }}"
        echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
        echo "ENV=$env" >> $GITHUB_ENV
        echo "CHART_PATH="${{ inputs.chart_path }}" >> $GITHUB_ENV
        echo "HELM_RELEASE=app-$app-$env" >> $GITHUB_ENV
        echo "NAMESPACE=app-$app-$env" >> $GITHUB_ENV

    - name: Set ref slug and chart ref slug
      shell: bash
      run: |
        echo "[DEBUG]: Setting ref slug and chart ref slug.."
        ref="${{ github.ref_name || github.event.release.tag_name }}"
        # Convert refs into slugs (allow . for ~v1.2.0)
        ref_slug=$(echo $ref \
          | tr '[:upper:]' '[:lower:]' \
          | sed -E 's/[^a-z0-9.]+/-/g' \
          | sed -E 's/^-+|-+$//g')
        echo "CHART_REF_SLUG=$ref_slug" >> $GITHUB_ENV
        echo "REF_SLUG=$ref_slug" >> $GITHUB_ENV

    - name: Set release version
      shell: bash
      run: |
        echo "[DEBUG]: Setting release version.."
        # If ref name is SEMVER-like, use it for release version
        if [[ $REF_SLUG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          release_version="$REF_SLUG"
        else
          release_version="$IMAGE_TAG"
        fi
        echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV

    - name: Set helm values
      shell: bash
      run: |
        echo "[DEBUG]: Setting helm values.."
        # Use custom values yaml file if exists. Otherwise, use values.dev.yaml
        envs_with_values="${{ inputs.envs_with_values }}"
        envs_with_values_regex=${envs_with_values//,/|}
        if [[ "${ENV}" = @($envs_with_values_regex) ]]; then
          helm_values="values.$ENV.yaml"
        else
          helm_values="values.dev.yaml"
        fi
        echo "HELM_VALUES=$helm_values" >> $GITHUB_ENV

    - name: Update helm chart appVersion to the deployed image sha
      shell: bash
      run: |
        sed -i \
          "s/^version:.*$/version: $CHART_REF_SLUG/" $CHART_PATH/Chart.yaml
        sed -i \
          "s/^appVersion:.*$/appVersion: $RELEASE_VERSION/" $CHART_PATH/Chart.yaml

    - name: Helm lint [np]
      if: ${{ inputs.cluster == 'np' }}
      uses: WyriHaximus/github-action-helm3@v2
      with:
        kubeconfig: "${{ inputs.kubeconfig_np }}"
        exec: |
          helm lint --strict \
            --set image.tag="$IMAGE_TAG" \
            --set envName="$ENV" \
            --set env="$ENV" \
            --namespace="$NAMESPACE" \
            --values="$CHART_PATH/$HELM_VALUES" \
            $CHART_PATH 1>&2

    - name: Helm lint [pr]
      if: ${{ inputs.cluster == 'np' }}
      uses: WyriHaximus/github-action-helm3@v2
      with:
        kubeconfig: "${{ inputs.kubeconfig_pr }}"
        exec: |
          helm lint --strict \
            --set image.tag="$IMAGE_TAG" \
            --set envName="$ENV" \
            --set env="$ENV" \
            --namespace="$NAMESPACE" \
            --values="$CHART_PATH/$HELM_VALUES" \
            $CHART_PATH 1>&2

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash


